import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [address, setAddress] = useState("");

  const airdrop = async () => {
    const response = await fetch("/api/airdrop", {
      method: "POST",
      body: JSON.stringify({ address }),
      headers: {
        "Content-Type": "application/json",
      },
    });

    if (!response.ok) return alert("Request failed!");

    const data = await response.json();

    alert(data.message);
  };

  return (
    <div
      style={{
        height: "100vh",
        width: "100vw",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <input
        type="text"
        style={{
          padding: "10px 20px",
          fontSize: "18px",
          width: "400px",
          outline: "none",
        }}
        value={address}
        onChange={(e) => setAddress(e.target.value)}
        placeholder="Wallet Address"
      />

      <button
        onClick={airdrop}
        style={{
          padding: "10px 20px",
          fontSize: "18px",
          width: "400px",
          marginTop: "10px",
          backgroundColor: "green",
          border: "none",
          borderRadius: "10px",
        }}
      >
        Airdrop 20 tokens to address
      </button>
    </div>
  );
}
